from typing import Protocol
from pathlib import Path
import numpy as np

class VectorBackend(Protocol):
    def add(self, embeddings: np.ndarray) -> None: ...
    def search(self, query: np.ndarray, k: int): ...
    def save(self, path: Path) -> None: ...
    @classmethod
    def load(cls, path: Path): ...
